sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: danm3swXBUltCWw0+CNplh6NsXEcZr4qTjG3r+uK5pDeuRsDrxGnOc5J3VUe9gssndgV1WMhasYuvUz3j7f7kBho6yN12Wq66ws2blpIlDub6t2fuyxT9jSxqz8CZ8I62LqLJz6loN7HkTt4wAIQUKk8/hKDRT7xZY82bid203JAdyHiQVAzs2FXHwlU7pBTwpmZ/zT3tkfWx8zWJQ1XQUP4AufbjrjG/6Z5uCa44CIG0/GVszxUQeP5kvh0Dydij3TtVxSbvVlylmdNOcxTKScCKZY8nKcPWtYFFiaVGdrqP03ALOKLfgMbW++cOVT0/dFuBTJc+/XSN8r2VvgL58bLPEV9zZ7HDQ93pXivjf1DfL3uFkWUCHV3BycH6asqPy5f/vK5OSlP1/EJwyrjqnFLW5dJIlVZu7sfhaFUbbiiGO8SsTqTqkFWCca52VJHJSiRWQMtW5ZQ97BDj5PY+pvOE9kcAXokViw+9E+i3IYvnBveGL7s9TpaP8eqEZ6EiaXwOSheefzN16uILg7iLSxwHGwGiWPciCewRndwYIc+FUmICcF3IbFT+kM0qJ2VaFpi2A9JkmbIO62XamQjEMGYtpwyxwcvIeAbvzv5JbWCY52Lsu0FBa1KMUsei6ksjpHvpApsVaYmhJXfKQ0nR0HSfZ/aJH6nK1z0b6+ifss=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-History-of-England-from-the-Accession-of-James-II---Volume-4_2613
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy